name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build folder
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSPIRIT_UI_CXX_USE_QT=OFF

    - name: build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Install python packages
      run: pip install --user numpy

    - name: test
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure